---
# -- Name for this DNS and DHCP server instance.
# @section -- General Settings
name: ""

# -- The value of the job label for scraped metrics
# @section -- General Settings
jobLabel: integration/dnsmasq

# Settings for metrics collection
metrics:
  # -- Whether to enable metrics collection from DNS and DHCP server.
  # @section -- Metrics Settings
  enabled: true

  # -- How frequently to scrape metrics.
  # @default -- `60s`
  # @section -- Scrape Settings
  scrapeInterval:

  # -- Sets the max_cache_size for prometheus.relabel component.
  # This should be at least 2x-5x your largest scrape target or samples appended rate.
  # ([docs](https://grafana.com/docs/alloy/latest/reference/components/prometheus.relabel/#arguments))
  # Overrides global.maxCacheSize
  # @default -- `100000`
  # @section -- Metric Processing Settings
  maxCacheSize:

  # Adjustments to the scraped metrics to filter the amount of data sent to storage.
  tuning:
    # -- Metrics to keep. Can use regular expressions.
    # @section -- Metric Processing Settings
    includeMetrics: []
    # -- Metrics to drop. Can use regular expressions.
    # @section -- Metric Processing Settings
    excludeMetrics: []

# Settings for the Alloy embedded DNS and DHCP server Exporter
exporter:
  # -- The address of the dnsmasq server.
  # @default -- `localhost:53`
  # @section -- Exporter Settings
  address: "localhost:53"
  
  # -- Path to dnsmasq leases file.
  # @default -- `/var/lib/misc/dnsmasq.leases`
  # @section -- Exporter Settings
  leasesPath: "/var/lib/misc/dnsmasq.leases"
