{{/* Do not edit this file. It is generated by the Makefile */}}
{{- define "integrations.types" -}}
- alloy
- apache
- blackbox
- cadvisor
- cert-manager
- consul
- dnsmasq
- elasticsearch
- etcd
- grafana
- kafka
- loki
- memcached
- mimir
- mongodb
- mssql
- mysql
- oracledb
- postgres
- redis
- snmp
- squid
- statsd
- tempo
{{- end -}}
