{{/* Elasticsearch secrets */}}
{{- range $instance := .Values.elasticsearch.instances }}
  {{- $instance = merge $instance (dict "type" "integration.elasticsearch") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.elasticsearch" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
{{/* Kafka secrets */}}
{{- range $instance := .Values.kafka.instances }}
  {{- $instance = merge $instance (dict "type" "integration.kafka") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.kafka" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
{{/* MongoDB secrets */}}
{{- range $instance := .Values.mongodb.instances }}
  {{- $instance = merge $instance (dict "type" "integration.mongodb") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.mongodb" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
{{/* MSSQL secrets */}}
{{- range $instance := .Values.mssql.instances }}
  {{- $instance = merge $instance (dict "type" "integration.mssql") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.mssql" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
{{/* OracleDB secrets */}}
{{- range $instance := .Values.oracledb.instances }}
  {{- $instance = merge $instance (dict "type" "integration.oracledb") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.oracledb" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
{{/* PostgreSQL secrets */}}
{{- range $instance := .Values.postgres.instances }}
  {{- $instance = merge $instance (dict "type" "integration.postgres") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.postgres" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
{{/* Redis secrets */}}
{{- range $instance := .Values.redis.instances }}
  {{- $instance = merge $instance (dict "type" "integration.redis") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (deepCopy $ | merge (dict "object" $instance)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (deepCopy $ | merge (dict "object" $instance)) | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.redis" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}